// <auto-generated />
namespace test1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_task));
        
        string IMigrationMetadata.Id
        {
            get { return "201505280916248_add_task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
